# from django.utils.translation import gettext_lazy as _

start_talk = f"📢 Assalomu alaykum! Men Developer Jobs kanali reklama menejeriman.\n\n ⚠️ Diqqat! Ushbu bot orqali faqat reklama berish istagida bo‘lganlar murojaat qilsin.\n\n 🚫 Boshqa mavzulardagi xabarlarga javob berilmaydi. Iltimos, ortiqcha bezovta qilmang!\n\n 💰 Developer Jobs kanalida reklama joylashtirish shartlari va narxlari:\n\n 👉 @defi_jobs_ads\n\n 📩 Samarali reklama uchun biz bilan bog‘laning! 🚀\n"

qaytish = "Qaytish"
company = "Kompaniya nomini kiriting:"
company2 = "Kompaniya nomi bo'sh bo'lishi mumkin emas. Iltimos, qayta kiriting:"
lavozim = "Lavozimni kiriting"
lavozim2 = "Lavozim bo'sh bo'lishi mumkin emas. Iltimos, qayta kiriting:"
maosh = "Maosh summasini kiriting"
ish_turi = "Ish turini kiriting"
all_data = "Qo'shimcha malumot kiriting"
manzil = "Manzilni kiriting"
lakatsiya = "Biokartadagi lakatsiyani kiriting, ixtiyoriy"
masul = "Mas'ul shaxsni kiriting"
lakatsiya2 = "Iltimos, lokatsiyani kiriting"
masul2 = "E'lon qancha muddat turishini belgilang (kunlarda, masalan: 30):"
save_error = "❌ Foydalanuvchi ma'lumotlarini saqlashda xatolik yuz berdi."
moderator = "Ma'lumotlaringiz Moderatorga junatildi."
state = "✅ Sizning vakansiyangiz qabul qilindi!"
cannel_save = "✅ Vakansiya tasdiqlandi va kanalga joylandi."
not_found = "⚠️ Vakansiya topilmadi."
error = "❌ Sizning vakansiyangiz rad etildi!"
error2 = "❌ Vakansiya rad etildi va o‘chirildi."
error3 = "⚠️ Vakansiya ID ni o'qishda xatolik yuz berdi. Iltimos, qayta urinib ko'ring."

image = "Resume faylini kiriting:"
please_image = "Iltimos, fayl yuboring."
qabul_qilish = "Rezyume qabul qilindi. Ko'nikmalaringiz haqida qo'shimcha ma'lumot kiriting."
error_resume = "❌ Foydalanuvchi ma'lumotlarini saqlashda xatolik yuz berdi."
to_disappaer = "❌ Fayl yo'qolgan yoki noto'g'ri holat."
return_admin = "Rezyume va qo'shimcha ma'lumot adminlarga yuborildi."
caption = "❌ Xabar caption (izoh) yo‘q."
id_not_found = "❌ Rezyume ID topilmadi.\nCaption:"
format_error = "❌ Rezyume ID noto‘g‘ri formatda.\nCaption:"
resume_not_found = "❌ Rezyume topilmadi. ID:"
succes = "✅ Rezyumeingiz qabul qilindi."
not_succes = "❌ Rezyume rad etildi."
channel_resume = "❌ Rezyume kanalga yuborishda xatolik yuz berdi."
error_1 = "❌ Rezyume xabarini o'chirishda xatolik yuz berdi."
candition = "Holat yangilandi."
no_recent_vacancies = "so'nggi bo'sh ish o'rinlari yo'q"

Kompaniya = "🏢 Kompaniya:"
Lavozim = "👤 Lavozim:"
Ish_turi = "🔹 Ish_turi:"
Maosh = "💰 Maosh:"
Qoshimcha = "ℹ Qo'shimcha ma'lumotlar:"
Manzil = "📍 Manzil:"
Lokatsiya = "🌎 Lokatsiya:"
Masul = "👤 Mas'ul:"


tanlang = "Tanlang"
bosh_menu = "🔙 Bosh Menu"

